name:                adventofcode2019
version:             0.1.0.0
github:              "Nicop06/adventofcode"
license:             BSD3
author:              "Nicolas Porcel"
maintainer:          "nicolasporcel06@gmail.com"
copyright:           "2025 Nicolas Porcel"

# Metadata used when publishing your package
# synopsis:            Solutions for the Advent of Code
# category:            bin

description: The solution for the adventofcode 2019.

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- hashtables
- array
- vector
- mtl
- text
- linear
- lens
- unordered-containers
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-type-defaults
- -XTupleSections

library:
  source-dirs: src

executables:
  aoc2019:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - adventofcode2019
