name:                adventofcode2016
version:             0.1.0.0
github:              "Nicop06/adventofcode"
license:             BSD3
author:              "Nicolas Porcel"
maintainer:          "nicolasporcel06@gmail.com"
copyright:           "2022 Nicolas Porcel"

# Metadata used when publishing your package
# synopsis:            Solutions for the Advent of Code
# category:            bin

description: The solution for the adventofcode 2016.

dependencies:
- base >= 4.7 && < 5
- parsec
- vector
- repa
- cryptohash-md5
- containers
- bytestring
- text
- aeson
- scientific

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-type-defaults
- -XImportQualifiedPost
- -XTupleSections
- -XTypeOperators
- -O3

library:
  source-dirs:
    - .

executables:
  aoc2016:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2016
    when:
    - condition: false
      other-modules: Paths_adventofcode2016
